//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace IIS.IAS
{
    using ICSSoft.STORMNET;


    // *** Start programmer edit section *** (Using statements)

    // *** End programmer edit section *** (Using statements)


    /// <summary>
    /// Category.
    /// </summary>
    // *** Start programmer edit section *** (Category CustomAttributes)

    // *** End programmer edit section *** (Category CustomAttributes)
    [AutoAltered()]
    [Caption("Категория")]
    [AccessType(ICSSoft.STORMNET.AccessType.none)]
    [View("CategoryE", new string[] {
            "Name as \'Name\'"})]
    [View("CategoryL", new string[] {
            "Name as \'Name\'"})]
    public class Category : ICSSoft.STORMNET.DataObject
    {

        private string fName;

        // *** Start programmer edit section *** (Category CustomMembers)

        // *** End programmer edit section *** (Category CustomMembers)


        /// <summary>
        /// Name.
        /// </summary>
        // *** Start programmer edit section *** (Category.Name CustomAttributes)

        // *** End programmer edit section *** (Category.Name CustomAttributes)
        [StrLen(255)]
        public virtual string Name
        {
            get
            {
                // *** Start programmer edit section *** (Category.Name Get start)

                // *** End programmer edit section *** (Category.Name Get start)
                string result = this.fName;
                // *** Start programmer edit section *** (Category.Name Get end)

                // *** End programmer edit section *** (Category.Name Get end)
                return result;
            }
            set
            {
                // *** Start programmer edit section *** (Category.Name Set start)

                // *** End programmer edit section *** (Category.Name Set start)
                this.fName = value;
                // *** Start programmer edit section *** (Category.Name Set end)

                // *** End programmer edit section *** (Category.Name Set end)
            }
        }

        /// <summary>
        /// Class views container.
        /// </summary>
        public class Views
        {

            /// <summary>
            /// "CategoryE" view.
            /// </summary>
            public static ICSSoft.STORMNET.View CategoryE
            {
                get
                {
                    return ICSSoft.STORMNET.Information.GetView("CategoryE", typeof(IIS.IAS.Category));
                }
            }

            /// <summary>
            /// "CategoryL" view.
            /// </summary>
            public static ICSSoft.STORMNET.View CategoryL
            {
                get
                {
                    return ICSSoft.STORMNET.Information.GetView("CategoryL", typeof(IIS.IAS.Category));
                }
            }
        }
    }
}

