//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace IIS.IAS
{
    using ICSSoft.STORMNET;


    // *** Start programmer edit section *** (Using statements)

    // *** End programmer edit section *** (Using statements)


    /// <summary>
    /// Comment.
    /// </summary>
    // *** Start programmer edit section *** (Comment CustomAttributes)

    // *** End programmer edit section *** (Comment CustomAttributes)
    [AutoAltered()]
    [Caption("Комментарий")]
    [AccessType(ICSSoft.STORMNET.AccessType.none)]
    [View("CommentE", new string[] {
            "CommentText as \'Comment text\'"})]
    public class Comment : ICSSoft.STORMNET.DataObject
    {

        private string fCommentText;

        private IIS.IAS.Incident fIncident;

        // *** Start programmer edit section *** (Comment CustomMembers)

        // *** End programmer edit section *** (Comment CustomMembers)


        /// <summary>
        /// CommentText.
        /// </summary>
        // *** Start programmer edit section *** (Comment.CommentText CustomAttributes)

        // *** End programmer edit section *** (Comment.CommentText CustomAttributes)
        [StrLen(255)]
        public virtual string CommentText
        {
            get
            {
                // *** Start programmer edit section *** (Comment.CommentText Get start)

                // *** End programmer edit section *** (Comment.CommentText Get start)
                string result = this.fCommentText;
                // *** Start programmer edit section *** (Comment.CommentText Get end)

                // *** End programmer edit section *** (Comment.CommentText Get end)
                return result;
            }
            set
            {
                // *** Start programmer edit section *** (Comment.CommentText Set start)

                // *** End programmer edit section *** (Comment.CommentText Set start)
                this.fCommentText = value;
                // *** Start programmer edit section *** (Comment.CommentText Set end)

                // *** End programmer edit section *** (Comment.CommentText Set end)
            }
        }

        /// <summary>
        /// мастеровая ссылка на шапку IIS.IAS.Incident.
        /// </summary>
        // *** Start programmer edit section *** (Comment.Incident CustomAttributes)

        // *** End programmer edit section *** (Comment.Incident CustomAttributes)
        [Agregator()]
        [NotNull()]
        [PropertyStorage(new string[] {
                "Incident"})]
        public virtual IIS.IAS.Incident Incident
        {
            get
            {
                // *** Start programmer edit section *** (Comment.Incident Get start)

                // *** End programmer edit section *** (Comment.Incident Get start)
                IIS.IAS.Incident result = this.fIncident;
                // *** Start programmer edit section *** (Comment.Incident Get end)

                // *** End programmer edit section *** (Comment.Incident Get end)
                return result;
            }
            set
            {
                // *** Start programmer edit section *** (Comment.Incident Set start)

                // *** End programmer edit section *** (Comment.Incident Set start)
                this.fIncident = value;
                // *** Start programmer edit section *** (Comment.Incident Set end)

                // *** End programmer edit section *** (Comment.Incident Set end)
            }
        }

        /// <summary>
        /// Class views container.
        /// </summary>
        public class Views
        {

            /// <summary>
            /// "CommentE" view.
            /// </summary>
            public static ICSSoft.STORMNET.View CommentE
            {
                get
                {
                    return ICSSoft.STORMNET.Information.GetView("CommentE", typeof(IIS.IAS.Comment));
                }
            }
        }
    }

    /// <summary>
    /// Detail array of Comment.
    /// </summary>
    // *** Start programmer edit section *** (DetailArrayDetailArrayOfComment CustomAttributes)

    // *** End programmer edit section *** (DetailArrayDetailArrayOfComment CustomAttributes)
    public class DetailArrayOfComment : ICSSoft.STORMNET.DetailArray
    {

        // *** Start programmer edit section *** (IIS.IAS.DetailArrayOfComment members)

        // *** End programmer edit section *** (IIS.IAS.DetailArrayOfComment members)


        /// <summary>
        /// Construct detail array.
        /// </summary>
        /// <summary>
        /// Returns object with type Comment by index.
        /// </summary>
        /// <summary>
        /// Adds object with type Comment.
        /// </summary>
        public DetailArrayOfComment(IIS.IAS.Incident fIncident) : 
                base(typeof(Comment), ((ICSSoft.STORMNET.DataObject)(fIncident)))
        {
        }

        public IIS.IAS.Comment this[int index]
        {
            get
            {
                return ((IIS.IAS.Comment)(this.ItemByIndex(index)));
            }
        }

        public virtual void Add(IIS.IAS.Comment dataobject)
        {
            this.AddObject(((ICSSoft.STORMNET.DataObject)(dataobject)));
        }
    }
}

