//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace IIS.IAS
{
    using ICSSoft.STORMNET;


    // *** Start programmer edit section *** (Using statements)

    // *** End programmer edit section *** (Using statements)


    /// <summary>
    /// Counter party.
    /// </summary>
    // *** Start programmer edit section *** (CounterParty CustomAttributes)

    // *** End programmer edit section *** (CounterParty CustomAttributes)
    [AutoAltered()]
    [Caption("Контрагент")]
    [AccessType(ICSSoft.STORMNET.AccessType.none)]
    [View("CounterPartyE", new string[] {
            "Name as \'Name\'",
            "Surname as \'Surname\'",
            "Position as \'Position\'",
            "Position.Name as \'Name\'"}, Hidden=new string[] {
            "Position.Name"})]
    [MasterViewDefineAttribute("CounterPartyE", "Position", ICSSoft.STORMNET.LookupTypeEnum.Standard, "", "Name")]
    [View("CounterPartyL", new string[] {
            "Name as \'Name\'",
            "Surname as \'Surname\'",
            "Position.Name as \'Name\'"})]
    public class CounterParty : ICSSoft.STORMNET.DataObject
    {

        private string fName;

        private string fSurname;

        private IIS.IAS.Position fPosition;

        // *** Start programmer edit section *** (CounterParty CustomMembers)

        // *** End programmer edit section *** (CounterParty CustomMembers)


        /// <summary>
        /// Name.
        /// </summary>
        // *** Start programmer edit section *** (CounterParty.Name CustomAttributes)

        // *** End programmer edit section *** (CounterParty.Name CustomAttributes)
        [StrLen(255)]
        public virtual string Name
        {
            get
            {
                // *** Start programmer edit section *** (CounterParty.Name Get start)

                // *** End programmer edit section *** (CounterParty.Name Get start)
                string result = this.fName;
                // *** Start programmer edit section *** (CounterParty.Name Get end)

                // *** End programmer edit section *** (CounterParty.Name Get end)
                return result;
            }
            set
            {
                // *** Start programmer edit section *** (CounterParty.Name Set start)

                // *** End programmer edit section *** (CounterParty.Name Set start)
                this.fName = value;
                // *** Start programmer edit section *** (CounterParty.Name Set end)

                // *** End programmer edit section *** (CounterParty.Name Set end)
            }
        }

        /// <summary>
        /// Surname.
        /// </summary>
        // *** Start programmer edit section *** (CounterParty.Surname CustomAttributes)

        // *** End programmer edit section *** (CounterParty.Surname CustomAttributes)
        [StrLen(255)]
        public virtual string Surname
        {
            get
            {
                // *** Start programmer edit section *** (CounterParty.Surname Get start)

                // *** End programmer edit section *** (CounterParty.Surname Get start)
                string result = this.fSurname;
                // *** Start programmer edit section *** (CounterParty.Surname Get end)

                // *** End programmer edit section *** (CounterParty.Surname Get end)
                return result;
            }
            set
            {
                // *** Start programmer edit section *** (CounterParty.Surname Set start)

                // *** End programmer edit section *** (CounterParty.Surname Set start)
                this.fSurname = value;
                // *** Start programmer edit section *** (CounterParty.Surname Set end)

                // *** End programmer edit section *** (CounterParty.Surname Set end)
            }
        }

        /// <summary>
        /// Counter party.
        /// </summary>
        // *** Start programmer edit section *** (CounterParty.Position CustomAttributes)

        // *** End programmer edit section *** (CounterParty.Position CustomAttributes)
        [PropertyStorage(new string[] {
                "Position"})]
        [NotNull()]
        public virtual IIS.IAS.Position Position
        {
            get
            {
                // *** Start programmer edit section *** (CounterParty.Position Get start)

                // *** End programmer edit section *** (CounterParty.Position Get start)
                IIS.IAS.Position result = this.fPosition;
                // *** Start programmer edit section *** (CounterParty.Position Get end)

                // *** End programmer edit section *** (CounterParty.Position Get end)
                return result;
            }
            set
            {
                // *** Start programmer edit section *** (CounterParty.Position Set start)

                // *** End programmer edit section *** (CounterParty.Position Set start)
                this.fPosition = value;
                // *** Start programmer edit section *** (CounterParty.Position Set end)

                // *** End programmer edit section *** (CounterParty.Position Set end)
            }
        }

        /// <summary>
        /// Class views container.
        /// </summary>
        public class Views
        {

            /// <summary>
            /// "CounterPartyE" view.
            /// </summary>
            public static ICSSoft.STORMNET.View CounterPartyE
            {
                get
                {
                    return ICSSoft.STORMNET.Information.GetView("CounterPartyE", typeof(IIS.IAS.CounterParty));
                }
            }

            /// <summary>
            /// "CounterPartyL" view.
            /// </summary>
            public static ICSSoft.STORMNET.View CounterPartyL
            {
                get
                {
                    return ICSSoft.STORMNET.Information.GetView("CounterPartyL", typeof(IIS.IAS.CounterParty));
                }
            }
        }
    }
}

