//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace IIS.IAS
{
    using ICSSoft.STORMNET;


    // *** Start programmer edit section *** (Using statements)

    // *** End programmer edit section *** (Using statements)


    /// <summary>
    /// Incident.
    /// </summary>
    // *** Start programmer edit section *** (Incident CustomAttributes)

    // *** End programmer edit section *** (Incident CustomAttributes)
    [AutoAltered()]
    [Caption("Инцидент")]
    [AccessType(ICSSoft.STORMNET.AccessType.none)]
    [View("IncidentE", new string[] {
            "ID as \'ID\'",
            "Status as \'Status\'",
            "SolveBefore as \'Solve before\'",
            "Caption as \'Caption\'",
            "Description as \'Description\'",
            "Responsible as \'Responsible\'",
            "Responsible.Name as \'Name\'",
            "CounterParty as \'Counter party\'",
            "CounterParty.Name as \'Name\'",
            "Category as \'Category\'",
            "Category.Name as \'Name\'"}, Hidden=new string[] {
            "Responsible.Name",
            "CounterParty.Name",
            "Category.Name"})]
    [AssociatedDetailViewAttribute("IncidentE", "Comment", "CommentE", true, "", "Comment", true, new string[] {
            ""})]
    [MasterViewDefineAttribute("IncidentE", "Responsible", ICSSoft.STORMNET.LookupTypeEnum.Standard, "", "Name")]
    [MasterViewDefineAttribute("IncidentE", "CounterParty", ICSSoft.STORMNET.LookupTypeEnum.Standard, "", "Name")]
    [MasterViewDefineAttribute("IncidentE", "Category", ICSSoft.STORMNET.LookupTypeEnum.Standard, "", "Name")]
    [View("IncidentL", new string[] {
            "ID as \'ID\'",
            "Status as \'Status\'",
            "SolveBefore as \'Solve before\'",
            "Caption as \'Caption\'",
            "Description as \'Description\'",
            "Responsible.Name as \'Name\'",
            "CounterParty.Name as \'Name\'",
            "Category.Name as \'Name\'"})]
    public class Incident : ICSSoft.STORMNET.DataObject
    {

        private string fCaption;

        private string fDescription;

        private int fID;

        private System.DateTime? fSolveBefore;

        private IIS.IAS.IncidentStatus fStatus;

        private IIS.IAS.Category fCategory;

        private IIS.IAS.CounterParty fCounterParty;

        private IIS.IAS.Responsible fResponsible;

        private IIS.IAS.DetailArrayOfComment fComment;

        // *** Start programmer edit section *** (Incident CustomMembers)

        // *** End programmer edit section *** (Incident CustomMembers)


        /// <summary>
        /// Caption.
        /// </summary>
        // *** Start programmer edit section *** (Incident.Caption CustomAttributes)

        // *** End programmer edit section *** (Incident.Caption CustomAttributes)
        [StrLen(255)]
        public virtual string Caption
        {
            get
            {
                // *** Start programmer edit section *** (Incident.Caption Get start)

                // *** End programmer edit section *** (Incident.Caption Get start)
                string result = this.fCaption;
                // *** Start programmer edit section *** (Incident.Caption Get end)

                // *** End programmer edit section *** (Incident.Caption Get end)
                return result;
            }
            set
            {
                // *** Start programmer edit section *** (Incident.Caption Set start)

                // *** End programmer edit section *** (Incident.Caption Set start)
                this.fCaption = value;
                // *** Start programmer edit section *** (Incident.Caption Set end)

                // *** End programmer edit section *** (Incident.Caption Set end)
            }
        }

        /// <summary>
        /// Description.
        /// </summary>
        // *** Start programmer edit section *** (Incident.Description CustomAttributes)

        // *** End programmer edit section *** (Incident.Description CustomAttributes)
        [StrLen(255)]
        public virtual string Description
        {
            get
            {
                // *** Start programmer edit section *** (Incident.Description Get start)

                // *** End programmer edit section *** (Incident.Description Get start)
                string result = this.fDescription;
                // *** Start programmer edit section *** (Incident.Description Get end)

                // *** End programmer edit section *** (Incident.Description Get end)
                return result;
            }
            set
            {
                // *** Start programmer edit section *** (Incident.Description Set start)

                // *** End programmer edit section *** (Incident.Description Set start)
                this.fDescription = value;
                // *** Start programmer edit section *** (Incident.Description Set end)

                // *** End programmer edit section *** (Incident.Description Set end)
            }
        }

        /// <summary>
        /// ID.
        /// </summary>
        // *** Start programmer edit section *** (Incident.ID CustomAttributes)

        // *** End programmer edit section *** (Incident.ID CustomAttributes)
        public virtual int ID
        {
            get
            {
                // *** Start programmer edit section *** (Incident.ID Get start)

                // *** End programmer edit section *** (Incident.ID Get start)
                int result = this.fID;
                // *** Start programmer edit section *** (Incident.ID Get end)

                // *** End programmer edit section *** (Incident.ID Get end)
                return result;
            }
            set
            {
                // *** Start programmer edit section *** (Incident.ID Set start)

                // *** End programmer edit section *** (Incident.ID Set start)
                this.fID = value;
                // *** Start programmer edit section *** (Incident.ID Set end)

                // *** End programmer edit section *** (Incident.ID Set end)
            }
        }

        /// <summary>
        /// SolveBefore.
        /// </summary>
        // *** Start programmer edit section *** (Incident.SolveBefore CustomAttributes)

        // *** End programmer edit section *** (Incident.SolveBefore CustomAttributes)
        public virtual System.DateTime? SolveBefore
        {
            get
            {
                // *** Start programmer edit section *** (Incident.SolveBefore Get start)

                // *** End programmer edit section *** (Incident.SolveBefore Get start)
                System.DateTime? result = this.fSolveBefore;
                // *** Start programmer edit section *** (Incident.SolveBefore Get end)

                // *** End programmer edit section *** (Incident.SolveBefore Get end)
                return result;
            }
            set
            {
                // *** Start programmer edit section *** (Incident.SolveBefore Set start)

                // *** End programmer edit section *** (Incident.SolveBefore Set start)
                this.fSolveBefore = value;
                // *** Start programmer edit section *** (Incident.SolveBefore Set end)

                // *** End programmer edit section *** (Incident.SolveBefore Set end)
            }
        }

        /// <summary>
        /// Status.
        /// </summary>
        // *** Start programmer edit section *** (Incident.Status CustomAttributes)

        // *** End programmer edit section *** (Incident.Status CustomAttributes)
        public virtual IIS.IAS.IncidentStatus Status
        {
            get
            {
                // *** Start programmer edit section *** (Incident.Status Get start)

                // *** End programmer edit section *** (Incident.Status Get start)
                IIS.IAS.IncidentStatus result = this.fStatus;
                // *** Start programmer edit section *** (Incident.Status Get end)

                // *** End programmer edit section *** (Incident.Status Get end)
                return result;
            }
            set
            {
                // *** Start programmer edit section *** (Incident.Status Set start)

                // *** End programmer edit section *** (Incident.Status Set start)
                this.fStatus = value;
                // *** Start programmer edit section *** (Incident.Status Set end)

                // *** End programmer edit section *** (Incident.Status Set end)
            }
        }

        /// <summary>
        /// Incident.
        /// </summary>
        // *** Start programmer edit section *** (Incident.Category CustomAttributes)

        // *** End programmer edit section *** (Incident.Category CustomAttributes)
        [PropertyStorage(new string[] {
                "Category"})]
        [NotNull()]
        public virtual IIS.IAS.Category Category
        {
            get
            {
                // *** Start programmer edit section *** (Incident.Category Get start)

                // *** End programmer edit section *** (Incident.Category Get start)
                IIS.IAS.Category result = this.fCategory;
                // *** Start programmer edit section *** (Incident.Category Get end)

                // *** End programmer edit section *** (Incident.Category Get end)
                return result;
            }
            set
            {
                // *** Start programmer edit section *** (Incident.Category Set start)

                // *** End programmer edit section *** (Incident.Category Set start)
                this.fCategory = value;
                // *** Start programmer edit section *** (Incident.Category Set end)

                // *** End programmer edit section *** (Incident.Category Set end)
            }
        }

        /// <summary>
        /// Incident.
        /// </summary>
        // *** Start programmer edit section *** (Incident.CounterParty CustomAttributes)

        // *** End programmer edit section *** (Incident.CounterParty CustomAttributes)
        [PropertyStorage(new string[] {
                "CounterParty"})]
        [NotNull()]
        public virtual IIS.IAS.CounterParty CounterParty
        {
            get
            {
                // *** Start programmer edit section *** (Incident.CounterParty Get start)

                // *** End programmer edit section *** (Incident.CounterParty Get start)
                IIS.IAS.CounterParty result = this.fCounterParty;
                // *** Start programmer edit section *** (Incident.CounterParty Get end)

                // *** End programmer edit section *** (Incident.CounterParty Get end)
                return result;
            }
            set
            {
                // *** Start programmer edit section *** (Incident.CounterParty Set start)

                // *** End programmer edit section *** (Incident.CounterParty Set start)
                this.fCounterParty = value;
                // *** Start programmer edit section *** (Incident.CounterParty Set end)

                // *** End programmer edit section *** (Incident.CounterParty Set end)
            }
        }

        /// <summary>
        /// Incident.
        /// </summary>
        // *** Start programmer edit section *** (Incident.Responsible CustomAttributes)

        // *** End programmer edit section *** (Incident.Responsible CustomAttributes)
        [PropertyStorage(new string[] {
                "Responsible"})]
        [NotNull()]
        public virtual IIS.IAS.Responsible Responsible
        {
            get
            {
                // *** Start programmer edit section *** (Incident.Responsible Get start)

                // *** End programmer edit section *** (Incident.Responsible Get start)
                IIS.IAS.Responsible result = this.fResponsible;
                // *** Start programmer edit section *** (Incident.Responsible Get end)

                // *** End programmer edit section *** (Incident.Responsible Get end)
                return result;
            }
            set
            {
                // *** Start programmer edit section *** (Incident.Responsible Set start)

                // *** End programmer edit section *** (Incident.Responsible Set start)
                this.fResponsible = value;
                // *** Start programmer edit section *** (Incident.Responsible Set end)

                // *** End programmer edit section *** (Incident.Responsible Set end)
            }
        }

        /// <summary>
        /// Incident.
        /// </summary>
        // *** Start programmer edit section *** (Incident.Comment CustomAttributes)

        // *** End programmer edit section *** (Incident.Comment CustomAttributes)
        public virtual IIS.IAS.DetailArrayOfComment Comment
        {
            get
            {
                // *** Start programmer edit section *** (Incident.Comment Get start)

                // *** End programmer edit section *** (Incident.Comment Get start)
                if ((this.fComment == null))
                {
                    this.fComment = new IIS.IAS.DetailArrayOfComment(this);
                }
                IIS.IAS.DetailArrayOfComment result = this.fComment;
                // *** Start programmer edit section *** (Incident.Comment Get end)

                // *** End programmer edit section *** (Incident.Comment Get end)
                return result;
            }
            set
            {
                // *** Start programmer edit section *** (Incident.Comment Set start)

                // *** End programmer edit section *** (Incident.Comment Set start)
                this.fComment = value;
                // *** Start programmer edit section *** (Incident.Comment Set end)

                // *** End programmer edit section *** (Incident.Comment Set end)
            }
        }

        /// <summary>
        /// Class views container.
        /// </summary>
        public class Views
        {

            /// <summary>
            /// "IncidentE" view.
            /// </summary>
            public static ICSSoft.STORMNET.View IncidentE
            {
                get
                {
                    return ICSSoft.STORMNET.Information.GetView("IncidentE", typeof(IIS.IAS.Incident));
                }
            }

            /// <summary>
            /// "IncidentL" view.
            /// </summary>
            public static ICSSoft.STORMNET.View IncidentL
            {
                get
                {
                    return ICSSoft.STORMNET.Information.GetView("IncidentL", typeof(IIS.IAS.Incident));
                }
            }
        }
    }
}

