//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace IIS.IAS
{
    using ICSSoft.STORMNET;


    // *** Start programmer edit section *** (Using statements)

    // *** End programmer edit section *** (Using statements)


    /// <summary>
    /// Incident status.
    /// </summary>
    // *** Start programmer edit section *** (IncidentStatus CustomAttributes)

    // *** End programmer edit section *** (IncidentStatus CustomAttributes)
    public enum IncidentStatus
    {

        // *** Start programmer edit section *** (IncidentStatus.Created CustomAttributes)

        // *** End programmer edit section *** (IncidentStatus.Created CustomAttributes)
        [Caption("Создан")]
        Created,

        // *** Start programmer edit section *** (IncidentStatus.Active CustomAttributes)

        // *** End programmer edit section *** (IncidentStatus.Active CustomAttributes)
        [Caption("В работе")]
        Active,

        // *** Start programmer edit section *** (IncidentStatus.Closed CustomAttributes)

        // *** End programmer edit section *** (IncidentStatus.Closed CustomAttributes)
        [Caption("Выполнен")]
        Closed,
    }
}

