//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace IIS.IAS
{
    using ICSSoft.STORMNET;


    // *** Start programmer edit section *** (Using statements)

    // *** End programmer edit section *** (Using statements)


    /// <summary>
    /// Position.
    /// </summary>
    // *** Start programmer edit section *** (Position CustomAttributes)

    // *** End programmer edit section *** (Position CustomAttributes)
    [AutoAltered()]
    [Caption("Должность")]
    [AccessType(ICSSoft.STORMNET.AccessType.none)]
    [View("PositionE", new string[] {
            "Name as \'Name\'"})]
    [View("PositionL", new string[] {
            "Name as \'Name\'"})]
    public class Position : ICSSoft.STORMNET.DataObject
    {

        private string fName;

        // *** Start programmer edit section *** (Position CustomMembers)

        // *** End programmer edit section *** (Position CustomMembers)


        /// <summary>
        /// Name.
        /// </summary>
        // *** Start programmer edit section *** (Position.Name CustomAttributes)

        // *** End programmer edit section *** (Position.Name CustomAttributes)
        [StrLen(255)]
        public virtual string Name
        {
            get
            {
                // *** Start programmer edit section *** (Position.Name Get start)

                // *** End programmer edit section *** (Position.Name Get start)
                string result = this.fName;
                // *** Start programmer edit section *** (Position.Name Get end)

                // *** End programmer edit section *** (Position.Name Get end)
                return result;
            }
            set
            {
                // *** Start programmer edit section *** (Position.Name Set start)

                // *** End programmer edit section *** (Position.Name Set start)
                this.fName = value;
                // *** Start programmer edit section *** (Position.Name Set end)

                // *** End programmer edit section *** (Position.Name Set end)
            }
        }

        /// <summary>
        /// Class views container.
        /// </summary>
        public class Views
        {

            /// <summary>
            /// "PositionE" view.
            /// </summary>
            public static ICSSoft.STORMNET.View PositionE
            {
                get
                {
                    return ICSSoft.STORMNET.Information.GetView("PositionE", typeof(IIS.IAS.Position));
                }
            }

            /// <summary>
            /// "PositionL" view.
            /// </summary>
            public static ICSSoft.STORMNET.View PositionL
            {
                get
                {
                    return ICSSoft.STORMNET.Information.GetView("PositionL", typeof(IIS.IAS.Position));
                }
            }
        }
    }
}

